Fix -Werror failures on GCC 7
* ../../../tests/src-evaluate.c:195:39: error: ‘)’ directive output may be truncated writing 1 byte into a region of size between 0
and 256 [-Werror=format-truncation=]
* ../../../examples/audio_out.c:395:3: error: ignoring return value of ‘write’, declared with attribute warn_unused_result
[-Werror=unused-result]